version: '2.3'
services:
  broker:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-uimaas:0.0.1-SNAPSHOT
    build: .
    ports:
    - 40003:61616
    - 40002:8080
    command:
    - "startBroker.sh"
    healthcheck:
      test: ["CMD", "/healthcheckBroker.sh"]
      interval: 10s
      timeout: 5s
      retries: 2
  service:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-uimaas:0.0.1-SNAPSHOT
    build: .
    command:
    - "java"
    - "-jar"
    - "/uima-as/jars/shared-uima-as-0.0.1-SNAPSHOT.jar"
    volumes:
    - "$PWD/jars:/uima-as/jars"
    #- "${SUP_LOG_FILES:-~/logs/}:"
    cpus: ${CORES_PER_MACHINE:-1}
    mem_limit: ${MEMORY_PER_MACHINE_IN_GB:-5}G
  submitter:
    image: srv-builder.fkie.fraunhofer.de:18006/gehring-master-uimaas:0.0.1-SNAPSHOT
    build: .
    command:
    - "java"
    - "-jar"
    - "/uima-as/classpath/shared-uima-as-0.0.1-SNAPSHOT.jar"
    - "--client"
    - "-d"
    - "${SUP_GUTENBERG_RATIO:-1.0}"
    - "--minSize"
    - "${FILESIZE_MIN:-0}"
    - "--maxSize"
    - "${FILESIZE_MAX:--1}"
    - "--pipelineId"
    - "${SUP_PIPELINE_ID:-0}"
    volumes:
    #- "$PWD/descriptors:/uima-as/descriptors"
    - "$PWD/jars:/uima-as/classpath"
    depends_on:
      broker:
        condition: service_healthy
      service:
        condition: service_started
  document-provider:
    image: httpd:alpine
    ports:
    - 40001:80
    volumes:
    - "${DOCUMENT_DIR:-~/documents}:/usr/local/apache2/htdocs"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "-O", "-", "-T", "1", "localhost"]
